In [4]:
# using python lists

import numpy as np
import time

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()   # note start time
add = [x+y for x,y in zip(l1, l2)]
end = time.time()   # note end time

print(add[0:10])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.16582655906677246


In [8]:
# using numpy array

import numpy as np
import time

size = 1_000_000
l1 = np.array(range(size))
l2 = np.array(range(size))

start = time.time()   # note start time
add = l1 + l2

end = time.time()   # note end time

print(add[0:10])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.005095005035400391


In [10]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
print("Shape: ", arr.shape)
print("Type: ", type(arr))

Shape:  (3, 3)
Type:  <class 'numpy.ndarray'>


In [24]:
import sys
 
list_data = list(range(1000))
numpy_data = np.array(list_data)
 
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [35]:
# Square of elements using lists
size = 1_000_000
li = list(range(size))

start = time.time()
list_square = [x**2 for x in li]
end = time.time()

print(end - start)

0.1699380874633789


In [36]:
# Square of elements using numpy
size = 1_000_000
arr1 = np.array(range(size))

start = time.time()
numpy_square = arr1 ** 2
end = time.time()

print(end - start)

0.0073125362396240234
