In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# array of zeros
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# array of ones
ones = np.ones((3, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# array of any number
    # np.full((size, size) , element)
n = np.full((4, 4), 7)
print(n)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
# Identity array

eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# add number in an specific range
# -> 2=start, 22=end, 2=add

arange = np.arange(2, 22, 2)
print(arange)

[ 2  4  6  8 10 12 14 16 18 20]


In [16]:
linespace = np.linspace(1, 100, 5)
print(linespace)

[  1.    25.75  50.5   75.25 100.  ]


In [22]:
myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(myArr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# operations 
print("Size: ", myArr.size)
print("Shape: ", myArr.shape)
print("Dimension: ", myArr.ndim)
print("Data type: ", myArr.dtype)

Size:  12
Shape:  (4, 3)
Dimension:  2
Data type:  int64


In [27]:
# change data type accoring to need
# explicit type : myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.float32)

In [28]:
reshaped = myArr.reshape((3, 4))
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
flattened = myArr.flatten()
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
