In [1]:
import numpy as np

In [7]:
myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(myArr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(myArr[2][1])
print(myArr[0][0])
print(myArr[1][1])

8
1
5


In [12]:
flat = myArr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
print(flat[3:6])  # [start : end-1]

[4 5 6]


In [18]:
print(flat[:5])  # [0 : end-1]

[1 2 3 4 5]


In [20]:
print(flat[2:])  # [start : end]

[ 3  4  5  6  7  8  9 10 11 12]


In [24]:
print(flat[::2])  # skip every [:n-1] element

[ 1  3  5  7  9 11]


Slicing returns a view, not a copy! Change affect the original array.
use can .copy() to create an copy of np.array

In [26]:
# fancy indexing.
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])

[1 3 5]


In [27]:
condition_indexing = arr[arr>2]
print(condition_indexing)

[3 4 5]
