In [1]:
import numpy as np

In [2]:
myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(myArr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
sumAxis = np.sum(myArr, axis=0) # axis=0, vertical 
print(sumAxis)

[22 26 30]


In [5]:
sumAxis1 = np.sum(myArr, axis=1) # axis=1, horizontal
print(sumAxis1)

[ 6 15 24 33]


In [8]:
print(myArr[0:3, 1:3])

[[2 3]
 [5 6]
 [8 9]]


In [13]:
arr3D = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr3D.shape)

(2, 2, 3)


In [ ]:
arr3D[]